error: used `panic!()` or assertion in a function that returns `Result`
  --> $DIR/panic_in_result_fn.rs:6:5
   |
LL | /     fn result_with_panic() -> Result<bool, String> // should emit lint
LL | |
LL | |     {
LL | |         panic!("error");
LL | |     }
   | |_____^
   |
   = help: `panic!()` or assertions should not be used in a function that returns `Result` as `Result` is expected to return an error instead of crashing
note: return Err() instead of panicking
  --> $DIR/panic_in_result_fn.rs:9:9
   |
LL |         panic!("error");
   |         ^^^^^^^^^^^^^^^
   = note: `-D clippy::panic-in-result-fn` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::panic_in_result_fn)]`

error: used `panic!()` or assertion in a function that returns `Result`
  --> $DIR/panic_in_result_fn.rs:53:1
   |
LL | / fn function_result_with_panic() -> Result<bool, String> // should emit lint
LL | |
LL | | {
LL | |     panic!("error");
LL | | }
   | |_^
   |
   = help: `panic!()` or assertions should not be used in a function that returns `Result` as `Result` is expected to return an error instead of crashing
note: return Err() instead of panicking
  --> $DIR/panic_in_result_fn.rs:56:5
   |
LL |     panic!("error");
   |     ^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

